# Generated by Django 3.2.3 on 2021-05-15 05:59

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20210514_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='studentName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Rollno',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phoneNum',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
        migrations.DeleteModel(
            name='Parent',
        ),
    ]
